source1:
  type: RosKinect
  module: 'object_recognition_ros.io'
  parameters:
    rgb_frame_id: camera_rgb_optical_frame
    rgb_image_topic: /camera/rgb/image_rect_color
    rgb_camera_info: /camera/rgb/camera_info
    depth_image_topic: /camera/depth_registered/image_raw
    depth_camera_info: /camera/depth_registered/camera_info

sink1:
  type: TablePublisher
  module: 'object_recognition_tabletop'
  inputs: [source1]

sink2:
  type: Publisher
  module: 'object_recognition_ros.io'
  inputs: [source1]


pipeline1:
  type: TabletopTableDetector
  module: 'object_recognition_tabletop'
  inputs: [source1]
  outputs: [sink1]
  parameters:
    table_detector:
        min_table_size: 4000
        plane_threshold: 0.01

pipeline2:
  type: TabletopObjectDetector
  module: 'object_recognition_tabletop'
  inputs: [source1, pipeline1]
  outputs: [sink2]
  parameters:
    object_ids: 'all'
    tabletop_object_ids: 'REDUCED_MODEL_SET'
    threshold: 0.85
    db:
      type: CouchDB
      root: http://localhost:5984
      collection: object_recognition

